# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files/ui/design_addauto.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 116)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_3.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7, 0, QtCore.Qt.AlignHCenter)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_carrier = QtWidgets.QLineEdit(Dialog)
        self.line_carrier.setMinimumSize(QtCore.QSize(0, 0))
        self.line_carrier.setObjectName("line_carrier")
        self.horizontalLayout_2.addWidget(self.line_carrier)
        self.line_kod = QtWidgets.QLineEdit(Dialog)
        self.line_kod.setObjectName("line_kod")
        self.horizontalLayout_2.addWidget(self.line_kod)
        self.line_mark = QtWidgets.QLineEdit(Dialog)
        self.line_mark.setObjectName("line_mark")
        self.horizontalLayout_2.addWidget(self.line_mark)
        self.line_autonum = QtWidgets.QLineEdit(Dialog)
        self.line_autonum.setObjectName("line_autonum")
        self.horizontalLayout_2.addWidget(self.line_autonum)
        self.line_trailernum = QtWidgets.QLineEdit(Dialog)
        self.line_trailernum.setObjectName("line_trailernum")
        self.horizontalLayout_2.addWidget(self.line_trailernum)
        self.line_driver_secname = QtWidgets.QLineEdit(Dialog)
        self.line_driver_secname.setObjectName("line_driver_secname")
        self.horizontalLayout_2.addWidget(self.line_driver_secname)
        self.line_driver_name = QtWidgets.QLineEdit(Dialog)
        self.line_driver_name.setObjectName("line_driver_name")
        self.horizontalLayout_2.addWidget(self.line_driver_name)
        self.line_driver_thirdname = QtWidgets.QLineEdit(Dialog)
        self.line_driver_thirdname.setObjectName("line_driver_thirdname")
        self.horizontalLayout_2.addWidget(self.line_driver_thirdname)
        self.line_tel = QtWidgets.QLineEdit(Dialog)
        self.line_tel.setObjectName("line_tel")
        self.horizontalLayout_2.addWidget(self.line_tel)
        self.line_note = QtWidgets.QLineEdit(Dialog)
        self.line_note.setObjectName("line_note")
        self.horizontalLayout_2.addWidget(self.line_note)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "ПЕРЕВІЗНИК"))
        self.label_10.setText(_translate("Dialog", "ІНД.КОД"))
        self.label_9.setText(_translate("Dialog", "МАРКА АВТО"))
        self.label_8.setText(_translate("Dialog", "ДЕРЖ № АВТО"))
        self.label_7.setText(_translate("Dialog", "ДЕРЖ № ПРИЧЕПА"))
        self.label_6.setText(_translate("Dialog", "ПРІЗВИЩЕ"))
        self.label_4.setText(_translate("Dialog", "ІМЯ"))
        self.label_3.setText(_translate("Dialog", "ПО-БАТЬКОВІ"))
        self.label_2.setText(_translate("Dialog", "ТЕЛЕФОН"))
        self.label.setText(_translate("Dialog", "ЗАМІТКИ"))

